name: trialdemo
description: My trial demo

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  get: ^4.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  # Service locator
  get_it: ^7.1.3
  # Bloc for state management
  flutter_bloc: ^7.0.1
  # Value equality
  equatable: ^2.0.2
  # Functional programming thingies
  dartz: ^0.10.0-nullsafety.2
  loading_overlay: ^0.3.0
  dropdown_search: ^0.6.1
  http: ^0.13.3
  # Date picker
  syncfusion_flutter_datepicker: ^19.1.66-beta

  # Local cache
  shared_preferences: ^2.0.6
  # Loading animation
  flutter_spinkit: ^5.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  flutter_dotenv: ^5.0.0
  connectivity: ^3.0.6
  google_fonts: ^2.1.0
  jwt_decoder: ^2.0.1
  back_button_interceptor: ^5.0.1
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.9

dev_dependencies:
  build_runner: ^2.0.4

  flutter_test:
    sdk: flutter
  mockito: ^5.0.9
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - .env
    - assets/img/splash.png
    - assets/img/avatar.png
